#!/usr/bin/env ruby

require 'scout'
require 'scout-ai'

$0 = "scout-ai #{$previous_commands.any? ? $previous_commands*" " + " " : "" }#{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF
Ask an LLM model

$ #{$0} [<options>] [<question>]

Use STDIN to add context to the question. The context can be referenced using
three dots '...'. The model will be prompted with the question, unless the
inline option is used. If the chat option is used, the response will be added
to the end of the file. If the file option is used the file contents will be
prepended before the question.  With the template option, the file will be read
as if it were the question, and the actual question will be placed under the
characters '???', if they are present.

-h--help Print this help
-t--template* Use a template
-c--chat* Follow a conversation
-i--imports* Chat files to import, separated by comma
-in--inline* Ask inline questions about a file
-f--file* Incorporate file at the start
-w--workflow* Add a workflow as a tool
-m--model* Model to use
-e--endpoint* Endpoint to use
-b--backend* Backend to use
-d--dry_run Dry run, don't ask
EOF
if options[:help]
  if defined? scout_usage
    scout_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

Log.severity = options.delete(:log).to_i if options.include? :log

file, chat, inline, imports, template, workflow, dry_run = IndiferentHash.process_options options, 
  :file, :chat, :inline, :imports, :template, :workflow, :dry_run

imports = imports.split(/,\s*/) if imports

question = ARGV * " "

if template
  if Open.exists?(template)
    template_question = Open.read(template)
  elsif Scout.questions[template].exists?
    template_question = Scout.questions[template].read
  elsif Scout.chats.system[template].exists?
    template_question = Scout.chats.system[template].read
  elsif Scout.chats[template].exists?
    template_question = Scout.chats[template].read
  end
  if template_question.include?('???')
    question = template_question.sub('???', question)
  elsif not question.empty?
    question = template_question + "\nuser: #{question}"
  else
    question = template_question
  end
end

if question.include?('...')
  context = file ? Open.read(file) : STDIN.read
  question = question.sub('...', context)
elsif file
  question = "<file basename=#{File.basename file}>[[[\n" + Open.read(file) + "\n]]]</file>"
end

if chat
  conversation = Open.exist?(chat)? LLM.chat(chat) : Chat.setup([])
  imports.each{|import| conversation.import import } if imports
  convo_options = LLM.options conversation
  conversation = question.empty? ? conversation : conversation +  LLM.chat(question)

  conversation = Chat.setup conversation
  conversation.message :tool, workflow if workflow

  if dry_run
    ppp LLM.print conversation
    exit 0
  end

  new = LLM.ask(conversation, convo_options.merge(options.merge(return_messages: true)))
  Open.open(chat, mode: 'a') do |f|
    f.puts LLM.print([{role: :user, content: question}]) unless question.empty?
    f.puts LLM.print(new)
  end
  puts LLM.purge(new).last[:content]
elsif inline

  file = Open.read inline

  new_file = ""
  while true
    pre, question, post =
      file.partition(/^\s*#\s*ask:(?:.*?)(?=^\s*[^\s#]|\z)/smu)

      break if question.empty?

    new_file << pre
    new_file << question
    clean_question = question.gsub('#', '').gsub(/\s+/,' ').sub(/.*ask:\s*/,'').strip
    chat = [
      {role: :system, content: "Write a succint reply with no commentary and no formatting."},
      {role: :user, content: "Find the following question as a comment in the file give a response to be placed inline: #{question}"},
      LLM.tag('file', file, inline)
    ]

    chat = Chat.chat(chat)

    imports.each{|import| chat.import import } if imports

    response = LLM.ask(LLM.chat(chat))
    new_file << <<-EOF
# Response start
#{response}
# Response end
    EOF
    file = post
  end
  new_file << file
  Open.write(inline, new_file)
else
  conversation = LLM.chat question
  conversation.message :tool, workflow if workflow
  puts LLM.ask(conversation, options)
end
