#!/usr/bin/env ruby
# frozen_string_literal: true

require 'scout-ai'

cmd = $previous_commands ?
  "scout #{$previous_commands.any? ? "#{$previous_commands * ' '} " : ''}#{File.basename(__FILE__)}" :
  $PROGRAM_NAME

options = SOPT.setup <<~EOF

Examine the provenance of a chat

$ #{cmd} [<options>] <filename> [<other|->]*

-h--help Print this help
EOF
if options[:help]
  if defined? scout_usage
    scout_usage
  else
    puts SOPT.doc
  end
  exit 0
end

help = IndiferentHash.process_options options, :help

filename, _ = ARGV

raise MissingParameterException, :filename if filename.nil?


chat = LLM.chat filename
require 'rbbt-util'

job = Path.setup(chat.jobs.first)
job = Step.load(job.find)

module Chat
  def self.trace(chat_list = @chats.values)
    Chat.trace_chats(chat_list)
  end

  def self.direct_entries(chat_list = @chats.values)
    trace(chat_list).select do |entry|
      meta = entry[:meta]
      next false if meta[:job]
      %w[pt ct tt].any? { |name| meta.include?(name) }
    end
  end

  def self.token_totals(chat_list = @chats.values)
    direct_entries(chat_list).each_with_object({ pt: 0, ct: 0, tt: 0 }) do |entry, totals|
      meta = entry[:meta]
      %w[pt ct tt].each { |name| totals[name.to_sym] += meta[name].to_i }
    end
  end

  def self._format_tokens(tokens)
  end

  def self.print_tokens(tokens)
    "prompt=#{Misc.human_number(tokens[:pt])} completion=#{Misc.human_number(tokens[:ct])} total=#{Misc.human_number(tokens[:tt])}"
  end

  def rec_chats
    chats = [self]
    chats + self.job_chats.inject([]){|acc,job| acc.concat job.rec_agent_chats; acc }
  end
  
  def jobs
    job_paths.collect{|path| Step.load path }
  end

  def self.provenance(chat_file, prov = {})
    return prov if prov.include? chat_file
    return prov unless Open.exists?(chat_file)
    chat = Chat.load chat_file
    chat.jobs.each do |job|
      prov[chat_file] ||= []
      Chat.job_agent_chat_files(job).each do |agent_chat_file|
        prov[chat_file] << agent_chat_file
        prov.merge(Chat.provenance(agent_chat_file, prov))
      end
      job.dependencies.each do |dep|
        prov.merge(Chat.provenance(dep.path, prov))
      end
    end
    prov
  end

  def self.provenance_chat_files(chat)
    provenance(chat).values.flatten.uniq + [chat]
  end

  def self.tokens(chat)
    chats = provenance_chat_files(chat).collect{|file| 
      @@chat_file ||= {}
      @@chat_file[file] ||= LLM.chat file 
      @@chat_file[file] ||= Chat.load file 
    }
    Chat.token_totals(chats)
  end

end

class Step
  def agent_chats
    Chat.job_agent_chat_files(self).collect{|file| Chat.load file }
  end
end

def load_chat(filename)
  @loaded_chat ||= {}
  @loaded_chat[filename] ||= 
    begin
      job = Step.load filename
      filename = job.path if job.done?
      Chat.load filename
    rescue
      Chat.load filename
    end
end

filename ||=  "~/git/workflows/SC26/chats/network_usecase/3.1.themes"
raise MissingParameterException, :filename if filename.nil?

def report_line(type, path = nil, info = {}, offset: 0)
  parts = []

  case type
  when :job
    parts << Log.color( :yellow, type.to_s)
  when :chat
    parts << Log.color( :green, type.to_s)
  else
    parts << Log.color( :red, type.to_s)
  end

  if info
    #parts << Log.fingerprint(info) if info
    tok_str ||= []
    tok_str << "total=#{Misc.human_number(info[:tt].to_i)}" if info[:tt]
    tok_str << "prompt=#{Misc.human_number(info[:pt].to_i)}" if info[:pt]
    tok_str << "cont=#{Misc.human_number(info[:ct].to_i)}" if info[:ct]

    parts << tok_str*" "
  end
  parts << Log.color( :blue, path.to_s) if path
  parts.unshift ' '*offset if offset && offset > 0
  parts * " "
end

def report(obj, seen = [], offset: 0, name: nil)

  if Step === obj
    return if seen.include? obj.path
    seen << obj.path
    tokens = Chat.tokens(obj.path)
    name = obj.path
    puts report_line :job, name, tokens, offset: offset
    Chat.job_agent_chat_files(obj).each do |agent_chat|
      agent_name = Misc.path_relative_to obj.file('log'), agent_chat
      agent_name.sub(/^(chats|society)\//, '')
      report(agent_chat, seen, offset: offset+1, name: agent_name)
    end
    jobs = obj.dependencies
  else
    return if seen.include? obj
    seen << obj
    tokens = Chat.tokens(obj)
    name = File.basename obj if name.nil?
    puts report_line :chat, name, tokens, offset: offset unless name == 'agent.chat'
    chat = Chat.load obj
    jobs = chat.jobs
  end

  jobs.each do |job|
    next if seen.include? job.path
    report(job, seen, offset: offset+1 )
  end
end

report filename
