#!/usr/bin/env ruby
# frozen_string_literal: true

require 'scout'

cmd = $previous_commands ?
  "scout #{$previous_commands.any? ? "#{$previous_commands * ' '} " : ''}#{File.basename(__FILE__)}" :
  $PROGRAM_NAME

options = SOPT.setup <<~EOF

Format a chat in word

$ #{cmd} [<options>] <chat> <word>

-h--help Print this help
-r--reference* Use a different reference.docx
-l--last Format only the last interaction
EOF
if options[:help]
  if defined? scout_usage
    scout_usage
  else
    puts SOPT.doc
  end
  exit 0
end

help, reference, last = IndiferentHash.process_options options, :help, :reference, :last

reference ||= Scout.share.word["reference.docx"].find

chat, word, _ = ARGV

raise MissingParameterException, :chat if chat.nil?

if word.nil?
  word = chat.sub(/\.(txt|chat|md)$/i, '') + '.docx'
end

messages = Chat.parse Open.read(chat)

if last
  messages = messages.select{|m| %w(user assistant).include? m[:role].to_s }[-2..-1]
end

out = [] 
messages.each do |message|
  IndiferentHash.setup(message)
  case message['role']
  when 'user'
    out.push <<-EOF

::: {custom-style="UserBlock"}

#{message['content']}

:::

    EOF
  when 'assistant'
    out.push message['content']
  else
    next
  end
end

TmpFile.with_file out * "\n", extension: :md do |markdown|
  CMD.cmd(:pandoc, "'#{markdown}' --reference-doc=#{reference} -o #{word}")
end
puts word
