# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scout-ai 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scout-ai".freeze
  s.version = "0.2.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "2025-03-19"
  s.description = "assorted functionalities to help scouts use AI".freeze
  s.email = "mikisvaz@gmail.com".freeze
  s.executables = ["scout-ai".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".vimproject",
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/scout-ai",
    "lib/scout-ai.rb",
    "lib/scout/llm/agent.rb",
    "lib/scout/llm/ask.rb",
    "lib/scout/llm/backends/huggingface.rb",
    "lib/scout/llm/backends/ollama.rb",
    "lib/scout/llm/backends/openai.rb",
    "lib/scout/llm/backends/openwebui.rb",
    "lib/scout/llm/backends/relay.rb",
    "lib/scout/llm/embed.rb",
    "lib/scout/llm/parse.rb",
    "lib/scout/llm/rag.rb",
    "lib/scout/llm/tools.rb",
    "lib/scout/llm/utils.rb",
    "questions/coach",
    "scout_commands/agent/ask",
    "scout_commands/llm/ask",
    "scout_commands/llm/process",
    "scout_commands/llm/template",
    "test/data/person/brothers",
    "test/data/person/identifiers",
    "test/data/person/marriages",
    "test/data/person/parents",
    "test/scout/llm/backends/test_huggingface.rb",
    "test/scout/llm/backends/test_ollama.rb",
    "test/scout/llm/backends/test_openai.rb",
    "test/scout/llm/backends/test_openwebui.rb",
    "test/scout/llm/backends/test_relay.rb",
    "test/scout/llm/test_agent.rb",
    "test/scout/llm/test_ask.rb",
    "test/scout/llm/test_embed.rb",
    "test/scout/llm/test_parse.rb",
    "test/scout/llm/test_rag.rb",
    "test/scout/llm/test_tools.rb",
    "test/scout/llm/test_utils.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mikisvaz/scout-ai".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.6.5".freeze
  s.summary = "AI gear for scouts".freeze
end

