# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scout-ai 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scout-ai".freeze
  s.version = "1.0.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "2025-06-05"
  s.description = "assorted functionalities to help scouts use AI".freeze
  s.email = "mikisvaz@gmail.com".freeze
  s.executables = ["scout-ai".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".vimproject",
    "LICENSE",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/scout-ai",
    "lib/scout-ai.rb",
    "lib/scout/llm/agent.rb",
    "lib/scout/llm/agent/chat.rb",
    "lib/scout/llm/ask.rb",
    "lib/scout/llm/backends/bedrock.rb",
    "lib/scout/llm/backends/huggingface.rb",
    "lib/scout/llm/backends/ollama.rb",
    "lib/scout/llm/backends/openai.rb",
    "lib/scout/llm/backends/openwebui.rb",
    "lib/scout/llm/backends/relay.rb",
    "lib/scout/llm/backends/responses.rb",
    "lib/scout/llm/chat.rb",
    "lib/scout/llm/embed.rb",
    "lib/scout/llm/parse.rb",
    "lib/scout/llm/rag.rb",
    "lib/scout/llm/tools.rb",
    "lib/scout/llm/utils.rb",
    "lib/scout/model/base.rb",
    "lib/scout/model/python/base.rb",
    "lib/scout/model/python/huggingface.rb",
    "lib/scout/model/python/huggingface/causal.rb",
    "lib/scout/model/python/huggingface/causal/next_token.rb",
    "lib/scout/model/python/huggingface/classification",
    "lib/scout/model/python/huggingface/classification.rb",
    "lib/scout/model/python/torch.rb",
    "lib/scout/model/python/torch/dataloader.rb",
    "lib/scout/model/python/torch/helpers.rb",
    "lib/scout/model/python/torch/introspection.rb",
    "lib/scout/model/python/torch/load_and_save.rb",
    "lib/scout/model/util/run.rb",
    "lib/scout/model/util/save.rb",
    "python/scout_ai/__init__.py",
    "python/scout_ai/__pycache__/__init__.cpython-310.pyc",
    "python/scout_ai/__pycache__/__init__.cpython-311.pyc",
    "python/scout_ai/__pycache__/huggingface.cpython-310.pyc",
    "python/scout_ai/__pycache__/huggingface.cpython-311.pyc",
    "python/scout_ai/__pycache__/util.cpython-310.pyc",
    "python/scout_ai/__pycache__/util.cpython-311.pyc",
    "python/scout_ai/atcold/__init__.py",
    "python/scout_ai/atcold/plot_lib.py",
    "python/scout_ai/atcold/spiral.py",
    "python/scout_ai/huggingface/data.py",
    "python/scout_ai/huggingface/eval.py",
    "python/scout_ai/huggingface/model.py",
    "python/scout_ai/huggingface/rlhf.py",
    "python/scout_ai/huggingface/train/__init__.py",
    "python/scout_ai/huggingface/train/__pycache__/__init__.cpython-310.pyc",
    "python/scout_ai/huggingface/train/__pycache__/next_token.cpython-310.pyc",
    "python/scout_ai/huggingface/train/next_token.py",
    "python/scout_ai/language_model.py",
    "python/scout_ai/util.py",
    "scout-ai.gemspec",
    "scout_commands/agent/ask",
    "scout_commands/agent/kb",
    "scout_commands/llm/ask",
    "scout_commands/llm/process",
    "scout_commands/llm/template",
    "test/data/cat.jpg",
    "test/data/person/brothers",
    "test/data/person/identifiers",
    "test/data/person/marriages",
    "test/data/person/parents",
    "test/scout/llm/agent/test_chat.rb",
    "test/scout/llm/backends/test_bedrock.rb",
    "test/scout/llm/backends/test_huggingface.rb",
    "test/scout/llm/backends/test_ollama.rb",
    "test/scout/llm/backends/test_openai.rb",
    "test/scout/llm/backends/test_openwebui.rb",
    "test/scout/llm/backends/test_relay.rb",
    "test/scout/llm/backends/test_responses.rb",
    "test/scout/llm/test_agent.rb",
    "test/scout/llm/test_ask.rb",
    "test/scout/llm/test_chat.rb",
    "test/scout/llm/test_embed.rb",
    "test/scout/llm/test_parse.rb",
    "test/scout/llm/test_rag.rb",
    "test/scout/llm/test_tools.rb",
    "test/scout/llm/test_utils.rb",
    "test/scout/model/python/huggingface/causal/test_next_token.rb",
    "test/scout/model/python/huggingface/test_causal.rb",
    "test/scout/model/python/huggingface/test_classification.rb",
    "test/scout/model/python/test_base.rb",
    "test/scout/model/python/test_huggingface.rb",
    "test/scout/model/python/test_torch.rb",
    "test/scout/model/python/torch/test_helpers.rb",
    "test/scout/model/test_base.rb",
    "test/scout/model/util/test_save.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mikisvaz/scout-ai".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.6.6".freeze
  s.summary = "AI gear for scouts".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<scout-rig>.freeze, [">= 0".freeze])
end

