# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scout-ai 1.1.4 ruby lib

Gem::Specification.new do |s|
  s.name = "scout-ai".freeze
  s.version = "1.1.4".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "1980-01-02"
  s.description = "assorted functionalities to help scouts use AI".freeze
  s.email = "mikisvaz@gmail.com".freeze
  s.executables = ["scout-ai".freeze]
  s.extra_rdoc_files = [
    "LICENSE",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".vimproject",
    "LICENSE",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/scout-ai",
    "doc/Agent.md",
    "doc/Chat.md",
    "doc/LLM.md",
    "doc/Model.md",
    "doc/RAG.md",
    "lib/scout-ai.rb",
    "lib/scout/llm/agent.rb",
    "lib/scout/llm/agent/chat.rb",
    "lib/scout/llm/agent/delegate.rb",
    "lib/scout/llm/agent/iterate.rb",
    "lib/scout/llm/ask.rb",
    "lib/scout/llm/backends/anthropic.rb",
    "lib/scout/llm/backends/bedrock.rb",
    "lib/scout/llm/backends/huggingface.rb",
    "lib/scout/llm/backends/ollama.rb",
    "lib/scout/llm/backends/openai.rb",
    "lib/scout/llm/backends/openwebui.rb",
    "lib/scout/llm/backends/relay.rb",
    "lib/scout/llm/backends/responses.rb",
    "lib/scout/llm/chat.rb",
    "lib/scout/llm/chat/annotation.rb",
    "lib/scout/llm/chat/parse.rb",
    "lib/scout/llm/chat/process.rb",
    "lib/scout/llm/chat/process/clear.rb",
    "lib/scout/llm/chat/process/files.rb",
    "lib/scout/llm/chat/process/options.rb",
    "lib/scout/llm/chat/process/tools.rb",
    "lib/scout/llm/embed.rb",
    "lib/scout/llm/mcp.rb",
    "lib/scout/llm/rag.rb",
    "lib/scout/llm/tools.rb",
    "lib/scout/llm/tools/call.rb",
    "lib/scout/llm/tools/knowledge_base.rb",
    "lib/scout/llm/tools/mcp.rb",
    "lib/scout/llm/tools/workflow.rb",
    "lib/scout/llm/utils.rb",
    "lib/scout/model/base.rb",
    "lib/scout/model/python/base.rb",
    "lib/scout/model/python/huggingface.rb",
    "lib/scout/model/python/huggingface/causal.rb",
    "lib/scout/model/python/huggingface/causal/next_token.rb",
    "lib/scout/model/python/huggingface/classification",
    "lib/scout/model/python/huggingface/classification.rb",
    "lib/scout/model/python/torch.rb",
    "lib/scout/model/python/torch/dataloader.rb",
    "lib/scout/model/python/torch/helpers.rb",
    "lib/scout/model/python/torch/introspection.rb",
    "lib/scout/model/python/torch/load_and_save.rb",
    "lib/scout/model/util/run.rb",
    "lib/scout/model/util/save.rb",
    "python/scout_ai/__init__.py",
    "python/scout_ai/huggingface/data.py",
    "python/scout_ai/huggingface/eval.py",
    "python/scout_ai/huggingface/model.py",
    "python/scout_ai/huggingface/rlhf.py",
    "python/scout_ai/huggingface/train/__init__.py",
    "python/scout_ai/huggingface/train/next_token.py",
    "python/scout_ai/util.py",
    "scout-ai.gemspec",
    "scout_commands/agent/ask",
    "scout_commands/agent/kb",
    "scout_commands/documenter",
    "scout_commands/llm/ask",
    "scout_commands/llm/process",
    "scout_commands/llm/server",
    "scout_commands/llm/template",
    "share/server/chat.html",
    "share/server/chat.js",
    "test/data/cat.jpg",
    "test/data/person/brothers",
    "test/data/person/identifiers",
    "test/data/person/marriages",
    "test/data/person/parents",
    "test/scout/llm/agent/test_chat.rb",
    "test/scout/llm/backends/test_anthropic.rb",
    "test/scout/llm/backends/test_bedrock.rb",
    "test/scout/llm/backends/test_huggingface.rb",
    "test/scout/llm/backends/test_ollama.rb",
    "test/scout/llm/backends/test_openai.rb",
    "test/scout/llm/backends/test_openwebui.rb",
    "test/scout/llm/backends/test_relay.rb",
    "test/scout/llm/backends/test_responses.rb",
    "test/scout/llm/chat/test_parse.rb",
    "test/scout/llm/chat/test_process.rb",
    "test/scout/llm/test_agent.rb",
    "test/scout/llm/test_ask.rb",
    "test/scout/llm/test_chat.rb",
    "test/scout/llm/test_embed.rb",
    "test/scout/llm/test_mcp.rb",
    "test/scout/llm/test_parse.rb",
    "test/scout/llm/test_rag.rb",
    "test/scout/llm/test_tools.rb",
    "test/scout/llm/test_utils.rb",
    "test/scout/llm/tools/test_call.rb",
    "test/scout/llm/tools/test_knowledge_base.rb",
    "test/scout/llm/tools/test_mcp.rb",
    "test/scout/llm/tools/test_workflow.rb",
    "test/scout/model/python/huggingface/causal/test_next_token.rb",
    "test/scout/model/python/huggingface/test_causal.rb",
    "test/scout/model/python/huggingface/test_classification.rb",
    "test/scout/model/python/test_base.rb",
    "test/scout/model/python/test_huggingface.rb",
    "test/scout/model/python/test_torch.rb",
    "test/scout/model/python/torch/test_helpers.rb",
    "test/scout/model/test_base.rb",
    "test/scout/model/util/test_save.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mikisvaz/scout-ai".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.7.0.dev".freeze
  s.summary = "AI gear for scouts".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<scout-rig>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<ruby-openai>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<ollama-ai>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<ruby-mcp-client>.freeze, [">= 0".freeze])
  s.add_runtime_dependency(%q<hnswlib>.freeze, [">= 0".freeze])
end

